version: "3.8"

services:
  backend:
    build: backend
    ports:
      - "${HTTP_PORT_BACKEND:-8000}:8000"
    depends_on:
      - database
    restart: always
    environment:
      - HTTP_HOST
      - HTTP_PORT
      - SECRET_KEY
      - DB_HOST
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_PORT
  database:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "127.0.0.1:${POSTGRES_PORT:-5432}:5432"
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
