# Generated by Django 4.0.1 on 2022-01-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mextrix_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='slug')),
                ('image', models.ImageField(default='courses/default_image_flying_disc.png', null=True, upload_to='courses', verbose_name='image')),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=18, verbose_name='longitude')),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=18, verbose_name='latitude')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'ordering': ['slug'],
            },
        ),
    ]
