# Generated by Django 4.0.1 on 2022-01-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='area',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='area'),
        ),
        migrations.AddField(
            model_name='course',
            name='city',
            field=models.CharField(db_index=True, max_length=255, null=True, verbose_name='city'),
        ),
    ]
