# Generated by Django 4.0.1 on 2022-01-19 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disc',
            options={'ordering': ['course', 'maker', 'model', 'color'], 'verbose_name': 'course', 'verbose_name_plural': 'courses'},
        ),
    ]
