# Generated by Django 4.0.1 on 2022-01-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disc', '0002_alter_disc_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disc',
            options={'ordering': ['course', 'maker', 'model', 'color'], 'verbose_name': 'disc', 'verbose_name_plural': 'discs'},
        ),
        migrations.AddField(
            model_name='disc',
            name='plastic',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
